food/urls.py
from django.urls import path
from . import views

app_name='food'
urlpatterns = [
    path('', views.index,name='index'),
    path('<int:item_id>/', views.detail, name='detail'),
    path('items/',views.items,name='items'),
    #add item
    #path('add',views.create_item,name='create_item'),
    path('add',views.CreateItem.as_view(),name='create_item'),
    path('update/', views.update, name='update', kwargs={'id': None}),
    path('update/<int:item_id>/',views.update,name='update'),
    path('delete/<int:item_id>/',views.delete,name='delete'),
]

mysite/urls.py
from django.contrib import admin
from django.urls import path,include
from users import views as users_view
from django.contrib.auth import views as authentication_view

from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    path('admin/', admin.site.urls),
    path('food/',include('food.urls')),
    path('register/',users_view.register,name='register'),
    path('login/',authentication_view.LoginView.as_view(template_name='users/login.html'),name='login'),
    path('logout/',authentication_view.LogoutView.as_view(template_name='users/logout.html'),name='logout'),
    path('profile/',users_view.profile,name='profile'),
]



urlpatterns += [

] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

food/models.py
from django.db import models
from django.contrib.auth.models import User
from django.urls import reverse

# Create your models here.

class Items(models.Model):
    item_name=models.CharField(max_length=200)
    item_desc=models.CharField(max_length=200)
    item_price=models.IntegerField()
    item_image=models.CharField(max_length=1000,default="https://cookinupastorm.biz/wp-content/uploads/2023/04/EmptyDinnerPlates.jpg")
    user_name=models.ForeignKey(User, on_delete=models.CASCADE, default=1)

    def __str__(self):
        return self.item_name
    
    
    def get_absolute_url(self):
        return reverse("food:index")


    

users/models.py
from django.db import models
from django.contrib.auth.models import User
# Create your models here.

class Profile(models.Model):
    user=models.OneToOneField(User,on_delete=models.CASCADE)
    image=models.ImageField(default='profile.png',upload_to='profilepictures')
    location=models.CharField(max_length=100)

    def __str__(self):
        return self.user.username

food/forms.py
from django import forms
from .models import Items

class ItemForm(forms.ModelForm):
    class Meta:
        model=Items
        fields=['item_name','item_desc','item_price','item_image']

users/forms.py
from django import forms
from django.contrib.auth.models import User
from django.contrib.auth.forms import UserCreationForm

class RegisterForm(UserCreationForm):
    email=forms.EmailField()

    class Meta:
        model=User
        fields=['username','email','password1','password2']

food/views.py
from django.shortcuts import render,redirect
from django.http import HttpResponse
from .models import Items
from django.template import loader
from .forms import ItemForm
from django.views.generic.edit import CreateView

def index(request):
    item_list=Items.objects.all()
    context={
        'item_list':item_list,
    }
    return render(request, 'food/index.html', context)

def items(request):
    return HttpResponse("This is an item view.")


def detail(request, item_id):
    item=Items.objects.get(id=item_id)
    context={
        'item':item,
    }
    return render(request, 'food/detail.html', context)

#def create_item(request):
    form=ItemForm(request.POST or None)
    

    if form.is_valid():
        form.save()
        return redirect('food:index')
    
    return render(request,'food/item-form.html',{'form':form})

#class based view for create item user association

class CreateItem(CreateView):
    model=Items
    fields= ['item_name','item_desc','item_price','item_image']
    template_name='food/item-form.html'
    
    def form_valid(self,form):
        form.instance.user_name=self.request.user
        
        return super().form_valid(form)

def update(request, item_id):
    item=Items.objects.get(id=item_id)
    form=ItemForm(request.POST or None, instance=item)

    if form.is_valid():
        form.save()
        return redirect('food:index')
    
    return render(request,'food/item-form.html',{'form':form,'item':item})

def delete(request,item_id):
    item=Items.objects.get(id=item_id)

    if request.method=='POST':
        item.delete()
        return redirect('food:index')
    
    return render(request,'food/delete-confirm.html',{'item':item})

users/views.py
from django.shortcuts import render,redirect
from .forms import RegisterForm
from django.contrib import messages
from requests import post
from django.contrib.auth.decorators import login_required

# Create your views here.

def register(request):
    if request.method=='POST':
        form=RegisterForm(request.POST)
        if form.is_valid():
            form.save()
            username=form.cleaned_data.get('username')
            messages.success(request,f'Welcome { username }, you are currently logged in !')
            return redirect('login')
    else:
        form=RegisterForm()
    return render(request,'users/register.html',{'form':form})

@login_required
def profile(request):
    return render(request,'users/profile.html')

food/templates/food/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
    <link rel="stylesheet" href="{% static 'food/style.css' %}">
</head>
<body style="background-color: white;">
    <nav class="navbar">
        <div class="navbar-brand"><h1 class="logo">FoodApp</h1></div>
        <div class="navbar-nav">
            <a href="{% url 'food:create_item' %}" style="color: blue;">Add Item</a>
            <a href="{% url 'food:index' %}" style="color: blue;">View Item</a>
            {% if user.is_authenticated %}
                <a href="{% url 'logout' %}" style="color: blue;">LogOut</a>
                <a href="{% url 'profile' %}" style="color: blue;">Profile</a>
            {% else %}
                <a href="{% url 'login' %}" style="color: blue;">LogIn</a>
            {% endif %}
        </div>
    </nav>
    {% if messages %}
        {% for message in messages %}
            <div style="background-color: lightgreen; color: black; text-align: center;">
                {{message}}
            </div>
        {% endfor %}
    {% endif %}
    
    {% block body %}
    {% endblock %}

</body>
</html>

food/templates/food/delete-confirm.html
<form method="POST">
    {% csrf_token %}
    
    <h2>Are you sure you want to delete {{ item.item_name }}</h2>
    <button type="submit">Confirm</button>
</form>

food/templates/food/detail.html
{% extends 'food/base.html' %}

    {% block body %}
        <div class="det-img">
            <center><img src="{{ item.item_image }}" height="400px" width="400px"></center>
        </div>
        <center>
        <div class="det">
            <h1>{{ item.item_name }}</h1>
            <h2>{{ item.item_desc }}</h2>
            <h3>Rs. {{ item.item_price }}</h3>
        </div>
        <div class="del">
            <a href="{% url 'food:delete' item.id %}"><button style="background-color: green; color: white; display: inline-block;">Delete</button></a>
        </div>
        </center>

    {% endblock %}

food/templates/food/index.html
{% extends 'food/base.html' %}

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
    
</head>
<body style="background-color: white;">
    
    
    {% block body %}

        {% for item in item_list %}
            
            <div class="row">
                <div class="col1" style="display: inline-block; margin-left: 15%; margin-top: 4%;">
                    <img class="card" src="{{ item.item_image }}" height="150px;" width="150px;">
                </div>

                <div class="col2" style="display: inline-block; margin-left: 16%;">
                    <h2>{{ item.item_name }}</h2>
                    <h3>{{ item.item_desc }}</h3>
                    <h4>{{ item.item_price }}</h4>
                    <h5>{{ item.user_name }}</h5>
                </div>

                <div class="col3" style="display: inline-block; margin-left: 60%;">
                    <a href="/food/{{item.id}}"><button style="background-color: green; color: white; display: inline-block;">Details</button></a>
                </div>

                <div class="col4" style="display: inline-block; margin-left: 60%">
                    <a href="/food/update/{{item.id}}"><button style="background-color: green; color: white; display: inline-block; width: 56px;">Update</button></a>
                </div>
                
            </div>
    
        {% endfor %}

    {% endblock %}   


    <ul>
            
        <li>  
            <a href="/food/{{item.id}}" style="text-decoration: none;">{{item.id}} -- {{item.item_name}}</a>
        </li>
    </ul>

</body>
</html>

food/templates/food/item-form.html
{% extends 'food/base.html' %}
{% block body %}
<form method="post">
    {% csrf_token %}
    <center>
        <div class="box" style="border: solid black 10px; background-color: rgba(196, 156, 252, 0.377);">
        {% for field in form %}
            <div class="row-name">
            <b>{{ field.name }}</b>
            </div>
            <div class="row-field">
            {{ field }}
            </div>
            <br>
        {% endfor %}
        <button type="submit" style="background-color: green; color: white;">Save</button>
    
        </div>
        </center>
    </div>
    
    

</form>
{% endblock %}

users/templates/users/login.html
{% extends 'food/base.html' %}

{% block body %}
<div class="container">
<form method="post">
    {% csrf_token %}
    <center>
    <div class="box" style="border: solid black 10px; background-color: rgba(196, 156, 252, 0.377);">
    {% for field in form %}
        <div class="row-name">
        <b>{{ field.name }}</b>
        </div>
        <div class="row-field">
        {{ field }}
        </div>
        <br>
    {% endfor %}
    <button type="submit" style="background-color: green; color: white;">LogIn</button>
</form>
    </div>
    </center>
</div>
{% endblock %}

users/templates/users/logout.html
<center>
    <h1><b>You have been logged out !</b></h1>
</center>

users/templates/users/profile.html
<center>
    <div class="prof" style="margin-top: 250px;">
    <img src="{{ user.profile.image.url }}" height="120px" width="120px" style="border: 5px solid black; border-radius: 100%;">
    <h1>{{ user.username }}</h1>
</center>
</div>

users/templates/users/register.html
{% extends 'food/base.html' %}

{% block body %}
<div class="container">
<form method="post">
    {% csrf_token %}
    <center>
        <div class="box" style="border: solid black 10px; background-color: rgba(196, 156, 252, 0.377);">
        {% for field in form %}
            <div class="row-name">
            <b>{{ field.name }}</b>
            </div>
            <div class="row-field">
            {{ field }}
            </div>
            <br>
        {% endfor %}
        <button type="submit" style="background-color: green; color: white;">LogIn</button>
    </form>
        </div>
        </center>
    </div>
    {% endblock %}
    

    <button type="submit">SignUp</button>
</form>